# Define o caminho para acessar (ex: http://localhost:9090/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuração da URL do Banco 
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.settings.web-allow-others=true

# JPA and Hibernate Configuration 
spring.jpa.hibernate.ddl-auto=create
spring.jpa.generate-ddl=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Faz o Spring ler os arquivos SQL na pasta db
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true


#Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config